framework:
#    cache:
#        default_memcached_provider: "memcached://localhost:32768"
#        pools:
#            app.cache.products:
#                adapter: cache.adapter.memcached
#                public: true
