parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
        
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        
    App\Command\GetExchangeDataCommand:
        arguments:
            - '@App\Service\ExchangeWrapper'
        calls:
            - [setEntityManager, ['@doctrine.orm.entity_manager']]
            
    App\Service\ExchangeWrapper:
        arguments:
            - '@App\Service\Client\Client'
        calls:
            - [setProvider, ['@App\Provider\Mocky1\ProviderData']]
            - [setProvider, ['@App\Provider\Mocky2\ProviderData']]
